<DeleteItem>:
	orientation: 'vertical'
	BoxLayout:
		orientation: 'vertical'	
		#size_hint_y: None
		canvas.before:
			Color:
				rgba: 0.4,0.5,1,1
			Rectangle:
				pos: self.pos
				size: self.size
		Label:
			text: 'Are you sure you want to delete the item?'
			size: self.texture_size
		BoxLayout:
			orientation: 'horizontal'
			Button:
				text: 'Confirm'
				on_press: if root.DeleteItemDataBase(): root.ReturnBack()
			Button:
				text: 'Quit'
				on_press: root.ReturnBack()
